### ISSUE TITLE
Удаляются значения списка при использовании тега EditLinkedLists

### ISSUE THREAD

**Issue by ursus102** [processtech/runawfe-server#105]
[test_EditLinkedLists.zip](https://github.com/processtech/runawfe-server/files/1469469/test_EditLinkedLists.zip)

Добрый день!
Если на форме более одного тега EditLinkedLists, то после того, как значение в один из связанных списков внесены, а затем форма открывается вновь у того же пользователя и вновь сохраняется (выполняется) внесенные значения удаляются.
Сборка сервера от 14.11.2017 с последними обновлениями из ветки master
Пример процесса во вложении.
История процесса:
14.11.2017 08:09:26 
Переменная Список3.size проинициализирована значением 2
Переменная Список3[0] проинициализирована значением test1
Переменная Список3[1] проинициализирована значением test2
Переменная Список2.size проинициализирована значением 0
Переменная Список1.size проинициализирована значением 0
Задание Действие 1 выполнено пользователем Administrator
Управление ушло из Действие 1
Управление пошло по переходу Сохраниить
Управление пришло в Исключающий шлюз 1
Управление ушло из Исключающий шлюз 1
Управление пошло по переходу Переход1
Управление пришло в Действие 1
Создано задание Действие 1
Задание Действие 1 назначено исполнителю Administrator
14.11.2017 08:09:29 
Переменная Список3.size сменила значение на 0
Переменная Список3[0] была удалена
Переменная Список3[1] была удалена
Задание Действие 1 выполнено пользователем Administrator
Управление ушло из Действие 1
Управление пошло по переходу Сохраниить
Управление пришло в Исключающий шлюз 1
Управление ушло из Исключающий шлюз 1
Управление пошло по переходу Переход1
Управление пришло в Действие 1
Создано задание Действие 1
Задание Действие 1 назначено исполнителю Administrator
14.11.2017 08:09:35 
Задание Действие 1 выполнено пользователем Administrator
Управление ушло из Действие 1
Управление пошло по переходу Завершить
Управление пришло в Окончание
Процесс завершен

**Comment by ursus102** [comment]
Судя по всему значения в списках уменьшаются на количество строк в наименьшем списке.

**Comment by dofs197** [comment]
Была проблема с использованием более одного экземпляра компонента EditLinkedLists на одной форме.
Исправлено: https://github.com/processtech/runawfe-server/pull/107
