### ISSUE TITLE
SQL - обработчик

### ISSUE THREAD

**Issue by ursus102** [processtech/runawfe-server#115]
[select_detail.zip](https://github.com/processtech/runawfe-server/files/1589044/select_detail.zip)

Если в результате запроса возвращается только 1 строка с результатами и в обработчики в качестве переменной для записи результата выбрана Переменная_1 типа Список(Строка), то выскакивает ошибка:
`java.lang.RuntimeException: Unsupported array type class java.lang.Integer`

**Comment by dofs197** [comment]
Прошу прощения за задержку.
Проблема решена в ветке https://github.com/processtech/runawfe-server/tree/rm553.
Исправление передано на тестирование.

**Comment by dofs197** [comment]
https://github.com/processtech/runawfe-server/commit/5b7b359653ec56e3df069d8a8ff725431205a315
