### ISSUE TITLE
Ошибка синхронизации данных

### ISSUE THREAD

**Issue by ursus102** [processtech/runawfe-server#135]
Версия 4.3.0-SNAPSHOT
Сборка master, 2ca8b0a, 28.05.2018

Ошибка синхронизации данных

![image](https://user-images.githubusercontent.com/18651258/40616033-ca1a27dc-62a2-11e8-9d06-7cc4fae1f2fb.png)

**Comment by vromav** [comment]
У Вас и сервер и DevStudio из master от 28.05.2018 ?
Проверьте на текущих сборках из ветки master.

**Comment by ursus102** [comment]
Скачал последние сборки из master, сейчас все работает, можно закрывать. Спасибо.

- Сервер

Версия 4.3.1-SNAPSHOT
Сборка master, 732f8c0, 06.06.2018

- Дизайнер
![image](https://user-images.githubusercontent.com/18651258/41014636-2f42b9ce-6962-11e8-9cb2-d3e9d4d6c45e.png)
