### ISSUE TITLE
Связанные списки, список файлов

### ISSUE THREAD

**Issue by ursus102** [processtech/runawfe-server#76]
Добрый день, на сборке сервера (Версия 4.3.0-SNAPSHOT, Сборка 25.04.2017) выявилась проблема:
если создать таблицу из связанных списков, где одна из колонок это файлы, но при этом файл не загружать, то на следующем этапе - мультиподпроцесс по переменной, процесс выдаёт ошибку: List has insufficient size, index = 0. Если же файл загрузить, то всё нормально. Ранее такого не было.
Кроме того, при добавлении строки в таблице, в списке файлов не создаётся элемент, и при пропуске допустим файла в первой строке, а загрузке во второй, после появления ошибки файл перепрыгивает на первую строку.
[Sourceforge RunaWFE Discussion](https://sourceforge.net/p/runawfe/discussion/426100/thread/fa2e73fa/)

**Comment by dofs197** [comment]
Исправлено в master.
